import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms of Service — CareerAI",
    description: "Terms and conditions for using the CareerAI platform.",
};

export default function TermsPage() {
    return (
        <main className="min-h-screen">
            <section className="pt-32 pb-12 px-4 container mx-auto max-w-3xl">
                <h1 className="text-4xl font-bold text-foreground mb-3">Terms of Service</h1>
                <p className="text-muted-foreground text-sm mb-10">Last updated: March 2025</p>

                <div className="space-y-8 text-sm">
                    <section>
                        <h2 className="text-lg font-bold mb-3 text-foreground">1. Acceptance of Terms</h2>
                        <p className="text-muted-foreground leading-relaxed">By creating an account or using CareerAI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-3 text-foreground">2. Description of Service</h2>
                        <p className="text-muted-foreground leading-relaxed">CareerAI provides AI-powered career guidance, including career exploration, personalized roadmaps, course recommendations, and an AI chat assistant. The service is intended for educational and informational purposes for students and young professionals.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-3 text-foreground">3. Eligibility</h2>
                        <p className="text-muted-foreground leading-relaxed">You must be at least 13 years old to use CareerAI. By using the Service, you represent that you meet this age requirement. Users under 18 should have parental consent.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-3 text-foreground">4. User Accounts</h2>
                        <p className="text-muted-foreground leading-relaxed">You are responsible for maintaining the security of your account and password. You agree to provide accurate information and to keep it updated. You must not share your account or allow others to access it. We reserve the right to suspend accounts that violate these terms.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-3 text-foreground">5. Acceptable Use</h2>
                        <p className="text-muted-foreground leading-relaxed mb-3">You agree not to:</p>
                        <ul className="list-disc list-inside text-muted-foreground space-y-2 leading-relaxed">
                            <li>Use the Service for any illegal purpose</li>
                            <li>Attempt to bypass rate limits or abuse the AI API</li>
                            <li>Share, scrape, or reproduce AI-generated content for commercial use without permission</li>
                            <li>Attempt to reverse-engineer or access the source code of the Service</li>
                            <li>Use automated scripts or bots to access the Service</li>
                            <li>Upload harmful, offensive, or misleading content</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-3 text-foreground">6. AI-Generated Content Disclaimer</h2>
                        <p className="text-muted-foreground leading-relaxed">Career recommendations, roadmaps, and course suggestions are generated by AI and are for informational purposes only. They do not constitute professional career counselling advice. CareerAI is not liable for decisions made based on AI-generated content. Always verify information and consider consulting a qualified career counsellor for critical decisions.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-3 text-foreground">7. Intellectual Property</h2>
                        <p className="text-muted-foreground leading-relaxed">The CareerAI platform, including its design, code, and branding, is the intellectual property of the CareerAI team. You retain ownership of the profile data you provide. You grant CareerAI a non-exclusive licence to use this data to provide the Service.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-3 text-foreground">8. Limitation of Liability</h2>
                        <p className="text-muted-foreground leading-relaxed">CareerAI is provided "as is" without warranties of any kind. We do not guarantee the accuracy, completeness, or timeliness of AI-generated content. To the maximum extent permitted by law, CareerAI will not be liable for any indirect, incidental, or consequential damages arising from use of the Service.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-3 text-foreground">9. Termination</h2>
                        <p className="text-muted-foreground leading-relaxed">We reserve the right to suspend or terminate accounts that violate these terms at any time, without notice. You may close your account at any time by contacting us at <a href="mailto:support@careerai.app" className="text-primary underline underline-offset-2">support@careerai.app</a>.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-3 text-foreground">10. Changes to Terms</h2>
                        <p className="text-muted-foreground leading-relaxed">We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance. Major changes will be communicated via email to registered users.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-3 text-foreground">11. Governing Law</h2>
                        <p className="text-muted-foreground leading-relaxed">These Terms are governed by the laws of India. Any disputes will be subject to the exclusive jurisdiction of courts in India.</p>
                    </section>

                    <section>
                        <h2 className="text-lg font-bold mb-3 text-foreground">12. Contact</h2>
                        <p className="text-muted-foreground leading-relaxed">For questions about these Terms, contact us at{" "}
                            <a href="mailto:legal@careerai.app" className="text-primary underline underline-offset-2">legal@careerai.app</a>.
                        </p>
                    </section>
                </div>
            </section>
        </main>
    );
}
